ami_value = "ami-0e449927258d45bc4"
key_name = "Vijay-Test-Key-pair"
instance_type_value = "t2.micro"
instance_tag_value = "myterraform_instance"
tag_dev_value = "Dev"
client_name = "VJ"
s3_bucket_name = "my-new-s3-buckey-vjah"
s3_acl_input = "private"